*** Settings ***
Documentation   Sending plain text email via Gmail.
Resource        keywords.robot
Library         Library.py
Variables       variables.py
Library         RPA.Email.ImapSmtp    smtp_server=smtp.gmail.com    smtp_port=587
Library         RPA.Robocloud.Secrets
Library         RPA.JSON


*** Variables ***
${USERNAME}       correoorigen
${PASSWORD}       laclave
${RECIPIENT}      example@example.com
${SRCH}           "text to search"   
@{ACCIONES}    Create   List    borrartodo    responder  

*** Keyword *** 
Send emaill
    Send Message    sender=${secret}[username] 
    ...    recipients=${RECIPIENT}
    ...    subject=Message generated by robot
    ...    body=This is the body of the email.

*** Keyword *** 
List of Messages
    @{emails}  List Messages  SUBJECT "Ordenes"
    FOR  ${email}  IN  @{EMAILS}
        Log  ${email}[Subject]
        Log  ${email}[From]
        Log  ${email}[Date]
        Log  ${email}[Delivered-To]
        #Log  ${email}[Received]
        Log  ${email}[Has-Attachments]
        Log  ${email}[Body]
        #Log  ${email}[Authentication-Results]
        #Log  ${email}[Precedence]
        Log  ${email}[Message-ID]
        Log  ${email}[MIME-Version]
        #Log  ${email}[Content-type]
        ${emai}=    Agregar Cero    ${email}[Date]
        ${fecha}=    Comparar Fecha    ${emai}    ${DIA}
        IF    ${fecha} == True
            Run Keyword If   ${email}[Has-Attachments] == True
                ...    Save Attachment  ${email}  target_folder=${CURDIR}  overwrite=True
        ELSE
            Log To Console    La fecha no es igual.
        END
    END
    [Return]    @{emails}


*** Keyword *** 
Comprobacion
    [Arguments]    @{emails}
    FOR  ${email}  IN  @{EMAILS}
        ${emai}=    Agregar Cero    ${email}[Date]
        ${fecha}=    Comparar Fecha    ${emai}    ${DIA}
        IF    ${fecha} == True
            ${val}=   Set variable    ${email}[Body]
            ${val}=   Limpiar Json   ${val} 
            Log    ${val}
            ${json}=    Convert String to JSON    ${val}
        ELSE
            Log To Console    No son iguales.
        END
        Exit For Loop If    True == True
    END
            #ELSE IF    ${random} > ${NUMBER_TO_PASS_ON}
            #Log To Console    Too high.   
    #Con este string sirve: {"Ordenes": {"clave": "123456789", "accion": "borrartodo" }}

*** Keyword *** 
Comprobacion2
    #Corre solo en RCC, probado con rpaframework 9.5 y python 3.7.5
    ${json}=    Load JSON from file    ${CURDIR}${/}Ordenes.json
    Log    ${json}
    ${first_order_id}=    Get value from JSON    ${json}    $.Ordenes
    ${accion}=    Get value from JSON    ${json}    $.Ordenes.accion
    ${first_order_id}=    Get value from JSON    ${json}    $.Ordenes.clave
    # ${first_order_id} = 1
    ${all_ids}=    Get values from JSON    ${json}    $..accion
    @{names}=     Get values from JSON     ${json}   $..accion
    # ${all_ids} = [1, 2]
    ${json}=    Add to JSON    ${json}    $    {"idd": 3}
    ${json}=    Add to JSON    ${json}    @    {"iddd": 3}
    ${json}=    Add to JSON    ${json}    $.Ordenes    {"id": 3}
    # ${json} = {'orders': [{'id': 1}, {'id': 2}, '{"id": 3}']}
    ${json}=    Delete from JSON    ${json}    $.idd
    # ${json} = {'orders': [{'id': 1}, {'id': 2}]}
    ${json}=    Update value to JSON    ${json}    $.Ordenes.clave    001002003
    Save JSON to file    ${json}    ${CURDIR}${/}Ordenes2.json
    Log    ${json}
    Log    Done.    
    [Return]    ${accion}

*** Keyword *** 
Leer Accion
    [Arguments]    ${accion}
    Log    ${accion}
    Log    ${ACCIONES}
    FOR    ${ACC}    IN    @{ACCIONES}
        ${dato}=    Comparar accion    ${accion}    ${ACC}
        IF    ${dato} == True
            ${val}=   Set variable    ${ACC}
            Exit For Loop If    True == True
        ELSE
            ${val}=   Set variable    Ninguna
        END
    END    
    [Return]    ${val}

*** Tasks ***
Send test email
    Log  Hola
    Example Keyword
    Example Python Keyword
    ${secret}=    Get Secret    emailCredentials
    Authorize    account=${secret}[username]    password=${secret}[password2]
    #Send emaill
    @{emails}=    List of Messages
    Tipo Var    ${DIA}
    FOR  ${email}  IN  @{EMAILS}
        Tipo Var    ${email}[Date]
    END
    #Comprobacion   @{emails} 
    ${accion}=    Comprobacion2 
    ${respuesta}=    Leer Accion    ${accion}
